name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c17f0c610b3d4fda772f14e467e5cf7fbe8050f7d90451df2cbe255f629343b"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
