name = "Fabulously Optimized"
author = "robotkoer"
version = "6.5.0-alpha.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc022eddc98d8ac7e5085b15abd195ba90e077b18b9293f10cb0460e16dd138c"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
datapack-folder = "datapacks"
